### ISSUE TITLE
能否补充一下具体使用示例

### ISSUE THREAD

**Issue by founderLog** [gongxufan/mTxn#1]
作者你好，请问@MultiTransaction的用法和@Transactional是可以一起混用？有什么影响不？

**Comment by gongxufan** [comment]
用法其实很简单，就是以前用Transactional的地方都可以用这个注解。

如果混用的话，理论上没有影响在web项目中，我提交了springboot和mybatis相关类的改动。如果您有兴趣的话可以一起补充一些测试用例。
