### ISSUE TITLE
是否兼容Hibernate这个ORM框架？

### ISSUE THREAD

**Issue by founderLog** [gongxufan/mTxn#5]
我们现在用的Hibernate，但是web项目是mybatis。不知这块有相关测试吗？

**Comment by gongxufan** [comment]
> 我们现在用的Hibernate，但是web项目是mybatis。不知这块有相关测试吗？

Hibernate这块暂时没有使用到，理论上是可以的。环境提交测试和PR。

**Comment by gongxufan** [comment]
> 我们现在用的Hibernate，但是web项目是mybatis。不知这块有相关测试吗？

Hibernate这块暂时没有使用到，理论上是可以的。环境提交测试和PR。
